### PR TITLE
Reset state_dict after resume

### PR DESCRIPTION
**Pull request by vgurev**
<details>
  <summary><b>Reset of state_dict after resume. </b></summary>

- [ No] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [Yes] Did you read the [contributor guideline](https://github.com/Lightning-AI/lit-data/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ No] Did you make sure to update the docs?
- [No] Did you write any new necessary tests?

</details>

## What does this PR do?

Currently, resume from restart is triggered by a check that self._state_dict is not None when dataset iterator is created
```python
if self._state_dict:
            self._resume(workers_chunks, workers_intervals)
```
However, the self._state_dict is never reset after restart. At the next epoch, when a new dataset iterator is created, the resume is triggered again from the same state_dict. To fix this bug, I assign None to the self._state_dict after resume. 

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Yes

### CODE REVIEW

**Comment by tchaton** [comment]
Hey @vgurev. Great catch ! Can you add a test ?

**Comment by vgurev** [comment]
OK, I will

**Comment by bhimrazy** [comment]
Hi @vgurev,

Thanks for reporting the bug and getting started on it!

> fyi, this issue was also addressed in [PR #318](https://github.com/Lightning-AI/litdata/pull/318), which got released yesterday.
>so, I tested by commenting out the lines in `dataset.py` that seem to reset the state at the end of epoch: [L345](https://github.com/Lightning-AI/litdata/blob/36049a8998fae96f2cbfca2e6d58fc988124c30c/src/litdata/streaming/dataset.py#L345) and [L352](https://github.com/Lightning-AI/litdata/blob/36049a8998fae96f2cbfca2e6d58fc988124c30c/src/litdata/streaming/dataset.py#L352).

**Test script**
<details>
<summary>Create Optimized Dataset</summary>

```python
from litdata import optimize


def random_data(index):
    return index

if __name__ == "__main__":
    optimize(
        fn=random_data,
        inputs=list(range(100)),
        output_dir="my_optimized_dataset",
        num_workers=4,
        chunk_bytes="64MB",
    )
```
</details>

```python
from litdata import StreamingDataLoader, StreamingDataset

dataset = StreamingDataset("my_optimized_dataset")
dataloader = StreamingDataLoader(dataset, batch_size=4, num_workers=2)

for batch_idx, batch in enumerate(dataloader):
    if batch_idx == 10:
        break

assert dataset._state_dict is None
dataloader.load_state_dict(dataloader.state_dict())
assert dataset._state_dict is not None

for batch_idx, batch in enumerate(dataloader):
    pass
 
assert dataset._state_dict is None
```
After testing, I noticed that the state reset issue still occurs when `num_workers > 1`. 
> However, since this has already been addressed, please feel free to try it out with the latest release and let us know how it goes.

Thanks again for bringing this to our attention and contributing to the improvements!
cc: @tchaton

**Comment by tchaton** [comment]
> Hi @vgurev,
> 
> Thanks for reporting the bug and getting started on it!
> 
> > fyi, this issue was also addressed in [PR #318](https://github.com/Lightning-AI/litdata/pull/318), which got released yesterday.
> > so, I tested by commenting out the lines in `dataset.py` that seem to reset the state at the end of epoch: [L345](https://github.com/Lightning-AI/litdata/blob/36049a8998fae96f2cbfca2e6d58fc988124c30c/src/litdata/streaming/dataset.py#L345) and [L352](https://github.com/Lightning-AI/litdata/blob/36049a8998fae96f2cbfca2e6d58fc988124c30c/src/litdata/streaming/dataset.py#L352).
> 
> **Test script**
> 
> Create Optimized Dataset
> ```python
> from litdata import StreamingDataLoader, StreamingDataset
> 
> dataset = StreamingDataset("my_optimized_dataset")
> dataloader = StreamingDataLoader(dataset, batch_size=4, num_workers=2)
> 
> for batch_idx, batch in enumerate(dataloader):
>     if batch_idx == 10:
>         break
> 
> assert dataset._state_dict is None
> dataloader.load_state_dict(dataloader.state_dict())
> assert dataset._state_dict is not None
> 
> for batch_idx, batch in enumerate(dataloader):
>     pass
>  
> assert dataset._state_dict is None
> ```
> 
> After testing, I noticed that the state reset issue still occurs when `num_workers > 1`, which might be due to the multi-worker processing.
> 
> > However, since this has already been addressed, please feel free to try it out with the latest release and let us know how it goes.
> 
> Thanks again for bringing this to our attention and contributing to the improvements! cc: @tchaton

Yes, we need to reset it from the DataLoader when the stopIteration occurs with num_workers > 0

**Pull request closed without merging**
