### PR TITLE
Expose max download param

### LINKED ISSUE #321: Expose max_pre_download in StreamingDataset
## 🚀 Feature

max_pre_download is the maximum number of chunks that are pre-downloaded with Streaming Datasets. This parameter is not exposed to the user today.

### Motivation

[Streaming Datasets](https://github.com/Lightning-AI/litdata/blob/c97ed24e8001c3ee8676fc2256baef815eaf5ff9/src/litdata/streaming/dataset.py#L43) uses a [Cache object](https://github.com/Lightning-AI/litdata/blob/c97ed24e8001c3ee8676fc2256baef815eaf5ff9/src/litdata/streaming/dataset.py#L335) to call into a [Reader](https://github.com/Lightning-AI/litdata/blob/c97ed24e8001c3ee8676fc2256baef815eaf5ff9/src/litdata/streaming/cache.py#L141) which then controls the maximum [number of files that can be pre-downloaded](https://github.com/Lightning-AI/litdata/blob/c97ed24e8001c3ee8676fc2256baef815eaf5ff9/src/litdata/streaming/reader.py#L56) 

We have a use-case where we want to increase this parameter. 

### Pitch

Expose max_pre_download in `StreamingDataset` -> `Cache` -> `BinaryReader` -> `PrepareChunksThread` to make it easy for the user to set this parameter

### PR DESCRIPTION
**Pull request by animan42**
<details>
  <summary><b>Before submitting</b></summary>

- [  ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [✅] Did you read the [contributor guideline](https://github.com/Lightning-AI/lit-data/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [✅] Did you make sure to update the docs?
- [  ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes #321 .

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by animan42** [comment]
> Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)

Not yet, but hoping to here #321 :)

**Review by tchaton — APPROVED** [review]
Mind adding a dummy test ?

**Comment by animan42** [comment]
@tchaton when do we expect to have a cut with this PR released? We're currently working off of a custom wheel and would love to just have a new release with this change

**Comment by tchaton** [comment]
Hey [animan42](https://github.com/animan42), we made a release with your PR.

**Pull request merged**
