### PR TITLE
Feat: Add support for storing and reading dataset from HF

### LINKED ISSUE #247: Add support for storing and reading dataset from HF

### PR DESCRIPTION
**Pull request by bhimrazy**
<details>
  <summary><b>Before submitting</b></summary>

- [x] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lit-data/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes #247.

### Key Features
- Adds support for storing and reading datasets from HF

### Example Usage
Here’s a brief example of how to use this new feature:

**Step 1: Optimize the data**
```python
import numpy as np
from PIL import Image
import litdata as ld

def random_images(index):
    fake_images = Image.fromarray(np.random.randint(0, 256, (32, 32, 3), dtype=np.uint8))
    fake_labels = np.random.randint(10)

    # You can use any key: value pairs. Note that their types must not change between samples, and Python lists must
    # always contain the same number of elements with the same types.
    data = {"index": index, "image": fake_images, "class": fake_labels}

    return data

if __name__ == "__main__":
    # The optimize function writes data in an optimized format.
    ld.optimize(
        fn=random_images,                   # the function applied to each input
        inputs=list(range(1000)),           # the inputs to the function (here it's a list of numbers)
        output_dir="my_optimized_dataset",  # optimized data is stored here
        num_workers=4,                      # The number of workers on the same machine
        chunk_bytes="64MB"                  # size of each chunk
    )
```
**Step 2: Upload the data to the hugging face**
```
huggingface-cli upload my-org/my-repo ./my_optimized_dataset --repo-type dataset --token=hf_****
```
**Step 3: Stream the data during training**
```python
import litdata as ld

hf_storage_options={
    "use_auth_token": "hf_****" # or os.environ['HF_TOKEN']
}
dataset = ld.StreamingDataset('hf://datasets/my-org/my-repo', shuffle=True, storage_options=hf_storage_options)
dataloader = ld.StreamingDataLoader(dataset)

for sample in dataloader:
    img, cls = sample['image'], sample['class']
```

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by bhimrazy** [comment]
### This feature can be tested using the following script:
```python
from litdata import StreamingDataset
dataset = StreamingDataset("hf://datasets/bhimrazy/litdata-optimized-dataset/")
print(dataset[0])
```

It does not yet support nested directory structures, e.g., `bhimrazy/litdata-optimized-dataset/dataset-1/`.

**Comment by bhimrazy** [comment]
> #### Reading dataset feature can be further tested using the following script:
> ```python
> from litdata import StreamingDataset
> dataset = StreamingDataset("hf://datasets/bhimrazy/litdata-optimized-dataset/")
> print(dataset[0])
> ```
> 
> It does not yet support nested directory structures, e.g., `bhimrazy/litdata-optimized-dataset/dataset-1/`.

Now, it supports the nested folder structure as well.
```python
from litdata import StreamingDataset

dataset = StreamingDataset("hf://datasets/bhimrazy/litdata-nested-optimized/dataset-1")
print(dataset[0])
```

**Comment by bhimrazy** [comment]
Hi @tchaton,

I wanted to understand the storing process. 
Are we expecting to store the data directly through the `optimize` process using the `output_dir` parameter, as shown in the example below?

```python
from litdata import optimize

def compress(index):
    return index**2

if __name__ == "__main__":
    # Add some data
    optimize(
        fn=compress,
        inputs=list(range(100)),
        output_dir="hf://datasets/bhimrazy/litdata-optimized-dataset",
        num_workers=4,
        chunk_bytes="64MB",
    )
```

or, upload the optimized dataset using the Hugging Face CLI after creating it, like this?

```sh
huggingface-cli upload bhimrazy/litdata-optimized-dataset my_optimized_dataset --repo-type dataset
```

Thank you for your guidance!

**Comment by tchaton** [comment]
Hey @bhimrazy,

Great question. I don't think HF supports partial update, so it won't work with pushing chunks as they get created. If it does, then we can do 1.

Otherwise, 2 is great.

**Review by tchaton — APPROVED** [review]
Looks awesome !

**Pull request merged**
