### PR TITLE
Fix the serialization of scalar valued tensors

### LINKED ISSUE #424: Scalar torch Tensors not recognized by (NoHeader)TensorSerializer -> Serialized as Pickle
## 🐛 Bug

I noticed that some scalar valued torch tensors in my dataset are being inferred as Pickle datatype. A quick investigation revealed, that neither the TensorSerialize nor the NoHeaderTensorSerializer `can_serialize` scalar valued tensors due to the conditions `and len(item.shape) == 1` and `and len(item.shape) > 1` respectively. 

This is a quick fix and I'm happy to submit a PR. Am I correct to assume that a scalar valued tensor would best be serialized by the TensorSerializer? I think I recall that the NoHeaderTensorSerializer was designed specifically for LLM training use-cases?

### To Reproduce

Execute the following snippet and you'll see a console printout indicating that the ``['pickle']` data format` is inferred.

<details>
  <summary>Code sample</summary>

```python
import torch
from litdata import optimize


def fn(i):
    return torch.tensor(i, dtype=torch.float32)


if __name__ == "__main__":
    optimize(
        fn=fn,
        inputs=list(range(1000)),
        output_dir="litdata/test",
        chunk_bytes=f"{1}Mb",
    )

```

</details>

### Additional context

<details>
  <summary>Environment detail</summary>

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

</details>

### PR DESCRIPTION
**Pull request by enrico-stauss**
<details>
  <summary><b>Before submitting</b></summary>

- [x] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lit-data/blob/main/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes #424.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by enrico-stauss** [comment]
By the way, I was concerned for backwards compatibility so I ran a quick check and this fix does not break backwards compatibility. Users with datasets that contain scalar valued tensors and which serialized as pickle can still deserialize correctly.

**Review by tchaton — APPROVED** [review]
Love it ! Thanks @enrico-stauss

**Comment by tchaton** [comment]
@enrico-stauss Any feedbacks, suggestions about LitData so far ?

**Comment by enrico-stauss** [comment]
I haven't had very advanced use-cases but from what I can tell LitData works smoothly most of the times and if something comes up, it is a quick fix.

Will keep using it for the resource efficiency alone, so you'll probably see me around :)

**Comment by tchaton** [comment]
Hey @enrico-stauss. That's great. Would you be willing to post on social about LitData ? I am trying to promote it a bit this month.

**Comment by enrico-stauss** [comment]
I (intentionally) don't really have much of a social media presence, so I don't think I can help you here @tchaton.

**Pull request merged**
