### PR TITLE
Fix the NoHeaderTensorSerializer for 1D tensors (other than tokens)

### PR DESCRIPTION
**Pull request by enrico-stauss**
<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/lit-data/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

This is a hotfix for #92 but should probably not be considered a permanent solution.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by tchaton** [comment]
Hey [enrico-stauss](https://github.com/enrico-stauss), would you mind adding a test ?

**Comment by enrico-stauss** [comment]
> Hey [enrico-stauss](https://github.com/enrico-stauss), would you mind adding a test ?

Done. I'm not sure if there are any standards inplace for unit testing in this repository but I hope you find the test satisfactory.

**Comment by tchaton** [comment]
Hey @enrico-stauss, I pushed some changes to your branch. Mind reviewing it ?

**Comment by enrico-stauss** [comment]
Yeah I had a check first, where I would set up only if the 'self._dtype' property of the 'NoHeaderTensorSerializer' was not set but then I had issues if there were tensors of different dtypes within the dataset, as the serializer was the same object for all of them.

**Review by tchaton — APPROVED** [review]

**Comment by tchaton** [comment]
> Yeah I had a check first, where I would set up only if the 'self._dtype' property of the 'NoHeaderTensorSerializer' was not set but then I had issues if there were tensors of different dtypes within the dataset, as the serializer was the same object for all of them.

Yes, it is simpler to deepcopy the serializer and setup them up. This reduces chance for errors.

**Pull request merged**
